# Framework for running automated tests on Open Source Brain using Travis-CI.
# See https://github.com/OpenSourceBrain/osb-model-validation for more details


language: python
python:
     - "2.7"

env:
     - OMV_ENGINE=jNeuroML
     - OMV_ENGINE=jNeuroML_NEURON
     - OMV_ENGINE=jNeuroML_validatev1
     - OMV_ENGINE=jNeuroML_validate
     - OMV_ENGINE=NON_OMV_TESTS
     
install:
    # Required to run OMV tests
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V; export OMV_SUCCESS=$?; echo $OMV_SUCCESS
    - echo "Finished all OMV tests"
    - if [[ ${OMV_ENGINE} == "NON_OMV_TESTS" ]]; then echo "Continuing with tests not under OMV..."; else exit $OMV_SUCCESS; fi
    - echo "Running non OMV tests..."
    - python setup.py install
    
     #    Test readers
    - cd CElegans/pythonScripts
    - python OpenWormReader.py
    - python SpreadsheetDataReader.py
    
     #    Test regenerate connectome
    - python RegenerateConnectome.py

    
