# Framework for running automated tests on Open Source Brain using Travis-CI.
# See https://github.com/OpenSourceBrain/osb-model-validation for more details

sudo: false

addons:
  apt:
    packages:
       # Requirements for Neuron/OMV/etc
    - python-numpy 
    - python-scipy 
    - python-matplotlib 

language: python
python:
     - "2.7"

virtualenv:
    system_site_packages: true 

env:
     - OMV_ENGINE=jNeuroML
     - OMV_ENGINE=jNeuroML_NEURON
     - OMV_ENGINE=jNeuroML_validatev1
     - OMV_ENGINE=jNeuroML_validate
     - OMV_ENGINE=NON_OMV_TESTS

install:
    # Required to run OMV tests
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V; export OMV_SUCCESS=$?; echo $OMV_SUCCESS
    - echo "Finished all OMV tests"
    - if [[ ${OMV_ENGINE} == "NON_OMV_TESTS" ]]; then echo "Continuing with tests not under OMV..."; else exit $OMV_SUCCESS; fi
    - echo "Running non OMV tests..."
    - python setup.py install

    # Test readers
    - cd CElegans/pythonScripts

    # Install PyOpenWorm
    - git clone https://github.com/openworm/PyOpenWorm.git
    - cd PyOpenWorm
    - python setup.py install
    - cd ..

    # Testing RegenerateConnectome.py, SpreadsheetDataReader.py, OpenWormReader.py via py.test
    - py.test -vs python_script_tester.py
    
    # Testing c302
    - cd c302 
    - omv install pyNeuroML
    - python c302_IClamp.py A
